version: '3.8'

services:
#  postgres:
#    image: postgres
#    restart: always
#    environment:
#      POSTGRES_USER: myuser
#      POSTGRES_PASSWORD: mypassword
#      POSTGRES_DB: mydatabase

  postgresGis:
    image: mdillon/postgis
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
#      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"